### ISSUE TITLE
Quotation marks

### ISSUE THREAD

**Issue by adibender** [randy3k/R-Box#89]
In regular R files (R Extended Syntax) I get regular quotation marks `""`. 
In R Sweave Syntax within r-chunks I get ```''` which messes up the R-Code. 
Is there an option to change this?

**Comment by randy3k** [comment]
I guess it is because of the LaTeX package that you have installed. Did you install LaTeXTools or something similar?

**Comment by adibender** [comment]
You are right! Thank you!

**Comment by randy3k** [comment]
I have included a patch in 0c43a6236f70b4193598cc4377b7a70bd6f3eeca.

**Comment by adibender** [comment]
Just FYI, I noticed, that this behavior occurs when LaTeXBox is installed, while it does not, when only LaTexTools is installed. I Fixed by uninstalling LaTexBox.

**Comment by adibender** [comment]
Just realised, might have nothing to do with LaTeXbox, cannot figure out, how it decides when to use which type of quotation. May have to do with some other package

**Comment by randy3k** [comment]
I confirm that it may be an issue of LaTeXBox if R-Box was installed via Package Control since Sublime will first load `*.sublime-package` files in `Installed Packages` folder then the packages under `Packages` folder.

 LaTeXBox is deprecated in favor of LaTeXYZ. However, the same issue is still applied to LaTeXYZ and a fix will be released soon.

**Comment by adibender** [comment]
Great, thanks! I found out, that in most cases quotation marks work as expected, an exception, however, is when I type `"`, the closing quotation is automatically included:`""`, when I then start typing and accidentally delete the closing quotation, adding a closing quotation manually adds the wrong type `"asdf''` (similarly with the opening quotation). 

Not a huge problem for me though, and I think in general.
